Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.hostname = "acroueS"
    config.vm.network "private_network", ip: "192.168.56.110"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "acroueS"
        vb.memory = 2048
        vb.cpus = 2
    end

    config.vm.provision "shell", path: "scripts/server.sh"
end
