Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.define "acroueS" do |control|
        control.vm.hostname = "acroueS"
        control.vm.network "private_network", ip: "192.168.56.110"

        control.vm.provider "virtualbox" do |vb|
            vb.name = "acroueS"
            vb.memory = 2048
            vb.cpus = 2
        end

        control.vm.provision "shell", path: "scripts/server.sh"
    end

    config.vm.define "acroueSW" do |control|
        control.vm.hostname = "acroueSW"
        control.vm.network "private_network", ip: "192.168.56.111"

        control.vm.provider "virtualbox" do |vb|
            vb.name = "acroueSW"
            vb.memory = 512
            vb.cpus = 1
        end

        control.vm.provision "shell", path: "scripts/agent.sh", args: ["192.168.56.110"]
    end
end
