Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	end

	config.vm.define "acroueS" do |control|
		control.vm.hostname = "acroueS"
		control.vm.network "private_network", ip: 192.168.56.110
		control.vm.provider "virtual" do |vb|
			vb.name = "acroueS"
		end
	end

	config.vm.define "acroueSW" do |control|
		control.vm.hostname = "acroueSW"
		control.vm.network "private_network", ip: 192.168.56.111
		control.vm.provider "virtual" do |vb|
			vb.name = "acroueSW"
		end
	end
end
